# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "toe_core"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Menke"]
  s.date = "2012-03-22"
  s.description = "This is a reference implementation of the ToE (time-oriented events) data model in Ruby. ToE was designed to model multiple heterogeneous event streams resulting from linguistic and psychological experiments."
  s.email = "pmenke@googlemail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "assets/haml/toe.xml.haml",
    "lib/toe-core.rb",
    "lib/toe.rb",
    "lib/toe/gen.rb",
    "lib/toe/gen/random_document_generator.rb",
    "lib/toe/model.rb",
    "lib/toe/model/basic_toe_object.rb",
    "lib/toe/model/belongs_to_event_document.rb",
    "lib/toe/model/data.rb",
    "lib/toe/model/event.rb",
    "lib/toe/model/event_link.rb",
    "lib/toe/model/event_set.rb",
    "lib/toe/model/feature.rb",
    "lib/toe/model/head.rb",
    "lib/toe/model/interval_link.rb",
    "lib/toe/model/layer.rb",
    "lib/toe/model/layer_connector.rb",
    "lib/toe/model/layer_link.rb",
    "lib/toe/model/layer_structure.rb",
    "lib/toe/model/link.rb",
    "lib/toe/model/point_link.rb",
    "lib/toe/model/scale.rb",
    "lib/toe/model/scale_set.rb",
    "lib/toe/model/toe_document.rb",
    "lib/toe/porter.rb",
    "lib/toe/porter/toe_porter.rb",
    "lib/toe/toe_cache.rb",
    "nbproject/project.properties",
    "nbproject/project.xml",
    "test/assets/CompleteToeDocument.toe",
    "test/assets/OutputDocument.toe",
    "test/helper.rb",
    "test/test_generator.rb",
    "test/test_persistent_cache.rb",
    "test/test_toe-core.rb",
    "test/test_toe_porter.rb",
    "toe-core.gemspec"
  ]
  s.homepage = "http://github.com/pmenke/toe-core"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Ruby implementation of the ToE (time-oriented events) data model"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<libxml-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_development_dependency(%q<test-unit>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<libxml-ruby>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<test-unit>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<libxml-ruby>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<test-unit>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

